### ISSUE TITLE
连接超时了

### ISSUE THREAD

**Issue by shahai-g** [MoonshotAI/MoonshotAI-Cookbook#33]
@SneakyThrows
    public static String chat(@NonNull String model, @NonNull List<Message> messages,Integer tokens_n) {
        String requestBody = new JSONObject()
                .putOpt("model", model)
                .putOpt("messages", messages)
                .putOpt("stream", false)
                .putOpt("max_tokens",tokens_n)
                .toString();
        Request okhttpRequest = new Request.Builder()
                .url(CHAT_COMPLETION_URL)
                .post(RequestBody.create(requestBody, MediaType.get(ContentType.JSON.getValue())))
                .addHeader("Authorization", "Bearer " + API_KEY)
                .build();
        Call call = new OkHttpClient().newBuilder()
                .callTimeout(600, TimeUnit.SECONDS)
                .readTimeout(600, TimeUnit.SECONDS)
                .writeTimeout(600, TimeUnit.SECONDS)
                .connectTimeout(600, TimeUnit.SECONDS)
                .build().newCall(okhttpRequest);
        Response okhttpResponse = call.execute();
        BufferedReader reader = new BufferedReader(okhttpResponse.body().charStream());
        String line;
        String content = null;
        if ((line = reader.readLine()) != null) {
            System.out.println(line);

            content = Optional.of(JSONUtil.parseObj(line))
                    .map(x -> x.getJSONArray("choices"))
                    .filter(CollUtil::isNotEmpty)
                    .map(x -> (JSONObject) x.get(0))
                    .map(x -> x.getJSONObject("message"))
                    .map(x -> x.getStr("content"))
                    .orElse(null); // 使用 orElse 处理Optional为空的情况
        }
        if (content != null) {
//            System.out.println("content: " + content);
            return content; // 确保有内容时返回content
        } else {
            // 根据需要处理未获取到内容的情况，例如抛出异常或返回默认值
            throw new IllegalStateException("Failed to retrieve content from response");
            // 或者 return "默认回复内容";
        }

    }
         */
    @PostMapping("/data")
    public AjaxResult getContent(@RequestBody Map<String, String> request) {
        String prompt = request.get("prompt");
        String message = request.get("message");

        List<Message> messages = CollUtil.newArrayList(
                new Message(RoleEnum.system.name(), prompt),
                new Message(RoleEnum.user.name(), message)
        );

        String tokens = moonshotAiUtils.estimateTokenCount("moonshot-v1-8k", messages);
        Integer tokens_n = Optional.of(JSONUtil.parseObj(tokens))
                .map(x -> x.getJSONObject("data"))
                .map(x -> x.getInt("total_tokens"))
                .orElse(null);
        System.out.println(tokens_n);

        String response = moonshotAiUtils.chat("moonshot-v1-8k", messages,8192-tokens_n);
        System.out.println(response);
        return AjaxResult.success();
    }
报错
javax.net.ssl.SSLProtocolException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:839)
	at okio.InputStreamSource.read(JvmOkio.kt:94)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	... 14 common frames omitted

**Comment by lychees** [comment]
API 返回的报错是？
